import { useCallback, useEffect, useMemo, useState } from 'react';
import { Activity, CalendarDays, Camera, Check, CircleUserRound, Grid2X2, LayoutDashboard, Menu, MoreVertical, Play, RefreshCw, Search, Settings, Video, WifiOff, X } from 'lucide-react';
type CameraItem={id:number;name:string;location:string;model:string;status:'online'|'offline'|'unknown';enabled:boolean;last_seen:string|null};
type Recording={id:number;camera_id:number;filename:string;start_time:string;end_time:string;size_bytes:number;duration_seconds:number};
type View='overview'|'live'|'recordings'|'activity'|'settings';
const API=import.meta.env.VITE_API_URL??'http://localhost:8000/api/v1'; const today=new Date().toISOString().slice(0,10);
const date=(v:string)=>new Intl.DateTimeFormat('es-ES',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v)); const size=(n:number)=>`${(n/1024/1024).toFixed(1)} MB`;
export function App(){const [view,setView]=useState<View>('overview'),[cameras,setCameras]=useState<CameraItem[]>([]),[recordings,setRecordings]=useState<Recording[]>([]),[query,setQuery]=useState(''),[day,setDay]=useState(today),[loading,setLoading]=useState(true),[error,setError]=useState(''),[mobile,setMobile]=useState(false),[playing,setPlaying]=useState<Recording|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const [a,b]=await Promise.all([fetch(`${API}/cameras`),fetch(`${API}/recordings?day=${day}`)]);if(!a.ok||!b.ok)throw Error('No se pudo conectar con la API');setCameras(await a.json());setRecordings(await b.json())}catch(e){setError(e instanceof Error?e.message:'Error de conexión')}finally{setLoading(false)}},[day]); useEffect(()=>{load()},[load]);
 const filtered=useMemo(()=>cameras.filter(c=>`${c.name} ${c.location} ${c.model}`.toLowerCase().includes(query.toLowerCase())),[cameras,query]); const online=cameras.filter(c=>c.status==='online').length; const go=(v:View)=>{setView(v);setMobile(false)};
 const nav=[['overview','Overview',LayoutDashboard],['live','Live grid',Grid2X2],['recordings','Grabaciones',Video],['activity','Actividad',Activity]] as const;
 return <div className="shell"><aside className={mobile?'open':''}><div className="brand"><span className="brand-mark"><Camera size={19}/></span>watchtower</div><nav>{nav.map(([id,label,Icon])=><button key={id} className={view===id?'active':''} onClick={()=>go(id)}><Icon size={18}/>{label}</button>)}</nav><div className="side-bottom"><button className={view==='settings'?'active':''} onClick={()=>go('settings')}><Settings size={18}/> Ajustes</button><div className="user"><CircleUserRound/><span><b>Alex Morgan</b><small>Administrator</small></span></div></div></aside><main><header><button className="mobile" onClick={()=>setMobile(!mobile)}><Menu/></button><div><p className="eyebrow">Operations / {view}</p><h1>{view==='overview'?'Camera overview':view==='live'?'Live grid':view==='recordings'?'Grabaciones':view==='activity'?'Registro de actividad':'Ajustes'}</h1></div><div className="header-actions"><div className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar cámaras..."/></div><button className="icon-btn" onClick={load}><RefreshCw size={18}/></button><div className="avatar">AM</div></div></header>{error&&<div className="alert"><WifiOff size={16}/>{error}<button onClick={load}>Reintentar</button></div>}{view==='settings'?<SettingsView/>:view==='activity'?<ActivityView cameras={cameras}/>:view==='recordings'?<Recordings recordings={recordings} cameras={cameras} day={day} setDay={setDay} onPlay={setPlaying}/>:<><section className="summary"><div><span className="label">SYSTEM STATUS</span><strong><i className="pulse"/>{error?'Connection unavailable':'All systems operational'}</strong></div><div className="stats"><span><b>{online}</b> Online</span><span><b>{cameras.length-online}</b> Offline</span><span><b>{recordings.length}</b> Grabaciones</span></div></section><div className="toolbar"><div><h2>Live feeds</h2><p>Monitoriza tus cámaras conectadas en tiempo real.</p></div><label className="date"><CalendarDays size={16}/><input type="date" value={day} onChange={e=>setDay(e.target.value)}/></label></div>{loading?<div className="empty">Cargando cámaras…</div>:<div className="grid">{filtered.map(c=><CameraCard key={c.id} camera={c}/>)}</div>}{!loading&&!filtered.length&&<div className="empty">No hay cámaras que coincidan con tu búsqueda.</div>}<section className="recordings"><div><h2>Recent recordings</h2><p>Últimos eventos capturados por las cámaras.</p></div><button className="link" onClick={()=>go('recordings')}>Ver todas →</button></section></>}{playing&&<Player recording={playing} camera={cameras.find(c=>c.id===playing.camera_id)} onClose={()=>setPlaying(null)}/>}</main></div>}
function CameraCard({camera}:{camera:CameraItem}){return <article className="camera-card"><div className="feed"><div className="feed-top"><span className={`status ${camera.status}`}>{camera.status==='online'?'LIVE':'OFFLINE'}</span><span className="cam-id">CAM-{String(camera.id).padStart(2,'0')}</span></div>{camera.status==='online'?<div className="scene"><Camera size={42}/><span>Stream preview</span></div>:<div className="offline"><WifiOff size={30}/><span>Cámara desconectada</span><small>{camera.last_seen?`Última conexión: ${date(camera.last_seen)}`:'Sin conexión registrada'}</small></div>}<button className="expand"><Play size={14}/></button></div><div className="card-info"><div><h3>{camera.name}</h3><p>{camera.location}</p></div><MoreVertical size={17} className="more"/></div></article>}
function Recordings({recordings,cameras,day,setDay,onPlay}:{recordings:Recording[];cameras:CameraItem[];day:string;setDay:(s:string)=>void;onPlay:(r:Recording)=>void}){return <section className="panel"><div className="toolbar"><div><h2>Grabaciones</h2><p>Consulta y reproduce eventos archivados.</p></div><label className="date"><CalendarDays size={16}/><input type="date" value={day} onChange={e=>setDay(e.target.value)}/></label></div>{recordings.length?<div className="recording-list">{recordings.map(r=><div className="recording-row" key={r.id}><span className="recording-icon"><Video size={16}/></span><div><b>{r.filename}</b><small>{cameras.find(c=>c.id===r.camera_id)?.name??`Cámara ${r.camera_id}`} · {date(r.start_time)}</small></div><span className="meta">{Math.round(r.duration_seconds/60)} min · {size(r.size_bytes)}</span><button className="play" onClick={()=>onPlay(r)}><Play size={15}/> Reproducir</button></div>)}</div>:<div className="empty">No hay grabaciones para este día.</div>}</section>}
function Player({recording,camera,onClose}:{recording:Recording;camera?:CameraItem;onClose:()=>void}){return <div className="modal-backdrop" onClick={onClose}><div className="player" onClick={e=>e.stopPropagation()}><button className="close" onClick={onClose}><X/></button><video className="video-player" controls autoPlay src={`${API}/recordings/${recording.id}/stream`}><track kind="captions"/></video><h2>{camera?.name??recording.filename}</h2><p>{date(recording.start_time)} · {size(recording.size_bytes)}</p></div></div>}
function ActivityView({cameras}:{cameras:CameraItem[]}){return <section className="panel"><h2>Registro de actividad</h2><p className="muted">Estado actual de los dispositivos.</p><div className="activity-list">{cameras.map(c=><div key={c.id}><span className={`activity-dot ${c.status}`}/><div><b>{c.name} está {c.status==='online'?'en línea':'desconectada'}</b><small>{c.last_seen?date(c.last_seen):'Sin actividad reciente'}</small></div></div>)}</div></section>}
function SettingsView(){return <section className="panel settings"><h2>Ajustes</h2><p className="muted">Preferencias del panel y conexión.</p><label>URL de la API<input value={API} readOnly/></label><label>Actualización automática<select defaultValue="manual"><option value="manual">Manual</option><option value="30">Cada 30 segundos</option><option value="60">Cada minuto</option></select></label><div className="saved"><Check size={16}/> Configuración cargada correctamente</div></section>}
